// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn27JD52Ctl3rPYd6oElerGyHHdAB7cUQ',
    appId: '1:598559610460:web:f9e559ef3935a3e939f899',
    messagingSenderId: '598559610460',
    projectId: 'shebnksapp',
    authDomain: 'shebnksapp.firebaseapp.com',
    databaseURL: 'https://shebnksapp-default-rtdb.firebaseio.com',
    storageBucket: 'shebnksapp.appspot.com',
    measurementId: 'G-9QR1SP0N06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAME47KafkhVo9SsT27lghyq6yG1u1P_9o',
    appId: '1:865239668665:android:60717000cc72b682480868',
    messagingSenderId: '865239668665',
    projectId: 'shebanks-d375c',
    databaseURL: 'https://shebanks-d375c-default-rtdb.firebaseio.com/',
    storageBucket: 'gs://shebanks-d375c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7AyhZbZeUl65XCX_naOGZJZrgEKWUAMA',
    appId: '1:598559610460:ios:5a79ec7c2186615939f899',
    messagingSenderId: '598559610460',
    projectId: 'shebnksapp',
    databaseURL: 'https://shebnksapp-default-rtdb.firebaseio.com',
    storageBucket: 'shebnksapp.appspot.com',
    iosClientId: '598559610460-hc91iagqhv5ll9gr8ufjic6senac9k71.apps.googleusercontent.com',
    iosBundleId: 'org.dotconnectafrica.shebnks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7AyhZbZeUl65XCX_naOGZJZrgEKWUAMA',
    appId: '1:598559610460:ios:5a79ec7c2186615939f899',
    messagingSenderId: '598559610460',
    projectId: 'shebnksapp',
    databaseURL: 'https://shebnksapp-default-rtdb.firebaseio.com',
    storageBucket: 'shebnksapp.appspot.com',
    iosClientId: '598559610460-hc91iagqhv5ll9gr8ufjic6senac9k71.apps.googleusercontent.com',
    iosBundleId: 'org.dotconnectafrica.shebnks',
  );
}
